import js from "@eslint/js";
import parser from "@typescript-eslint/parser";
import preferArrowPlugin from "eslint-plugin-prefer-arrow";
import typescriptPlugin from "@typescript-eslint/eslint-plugin";
import jsdoc from 'eslint-plugin-jsdoc';

export default [
  {
    ignores: ["node_modules/**", "dist/**", "**/*.config.js", "**/*.config.mjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      parser,
      globals: {
        env: "writable",
        luxon: "off",
      },
    },
    plugins: {
      "prefer-arrow": preferArrowPlugin,
      typescriptPlugin,
      jsdoc,
    },
    rules: {
      ...js.configs.recommended.rules,
      "array-bracket-spacing": ["error", "never"],
      "array-callback-return": "error",
      "arrow-body-style": ["error", "as-needed"],
      "arrow-parens": ["error", "as-needed"],
      "block-scoped-var": "error",
      camelcase: ["error", { properties: "always" }],
      "class-methods-use-this": "off",
      "comma-dangle": ["error", "always-multiline"],
      complexity: ["error", 11],
      "computed-property-spacing": ["error", "never"],
      "consistent-return": "error",
      "consistent-this": "error",
      "default-case": ["error", { commentPattern: "^skip\\sdefault" }],
      "dot-notation": "error",
      "for-direction": "error",
      "func-style": ["error", "expression"],
      "getter-return": "error",
      "guard-for-in": "error",
      "implicit-arrow-linebreak": ["error", "beside"],
      indent: ["error", 4, { SwitchCase: 1 }],
      "linebreak-style": ["error", "unix"],
      "line-comment-position": ["error", "above"],
      "lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
      "max-depth": ["error", 4],
      "max-len": ["error", { code: 120 }],
      "multiline-ternary": ["error", "always-multiline"],
      "newline-per-chained-call": "off",
      "no-alert": "error",
      "no-await-in-loop": "error",
      "no-case-declarations": "error",
      "no-catch-shadow": "error",
      "no-confusing-arrow": ["error", { allowParens: true }],
      "no-console": "error",
      "no-div-regex": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "error",
      "no-empty": "error",
      "no-empty-function": "error",
      "no-eq-null": "error",
      "no-extra-semi": "error",
      "no-floating-decimal": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-invalid-this": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-multi-assign": "error",
      "nonblock-statement-body-position": ["error", "beside"],
      "no-negated-condition": "error",
      "no-nested-ternary": "error",
      "no-prototype-builtins": "error",
      "no-script-url": "error",
      "no-underscore-dangle": "off",
      "no-useless-concat": "error",
      "no-unused-vars": "error",
      "no-var": "error",
      "no-void": "error",
      "no-warning-comments": ["error", { terms: ["todo", "fix", "fixme"] }],
      "no-throw-literal": "off",
      "object-curly-newline": "off",
      "object-curly-spacing": ["error", "always"],
      "object-shorthand": "error",
      "prefer-arrow/prefer-arrow-functions": ["error"],
      "prefer-const": "error",
      "prefer-numeric-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      radix: "error",
      "require-await": "error",
      "jsdoc/require-jsdoc": [
        "off",
        { require: { FunctionDeclaration: true, MethodDefinition: true, ClassDeclaration: true, ArrowFunctionExpression: false, FunctionExpression: true } },
      ],
      "require-yield": "error",
      "rest-spread-spacing": ["error", "never"],
      semi: ["error", "always"],
      "semi-style": ["error", "last"],
      "sort-imports": "off",
      "sort-keys": "off",
      "sort-vars": "off",
      "space-before-function-paren": "off",
      "switch-colon-spacing": "error",
      "valid-jsdoc": [
        "off",
        { prefer: { arg: "param", argument: "param", class: "constructor", return: "returns", virtual: "abstract" }, requireReturn: false },
      ],
      "wrap-regex": "error",
    },
  },
];
